name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: true
            fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
            hugo-version: '0.127.0'
            extended: false

      - name: Build
        run: hugo \
              --minify \
              --baseURL="${{ steps.pages.outputs.base_url }}/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./public
            publish_branch: gh-pages
            force_orphan: true
            full_commit_message: ${{ github.event.head_commit.message }}